notifications:
  email:
    on_success: always # default: change
    on_failure: always # default: always

sudo: required

services:
  - docker

script:
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker build -t facerec_service .;
  docker tag facerec_service eifinger/face_recognition:latest;
  docker push eifinger/face_recognition:latest;
